services:
  logseq:
    image: datalust/seq:latest
    container_name: datatracking-seq
    volumes:
       - ./.containers/seq:/data
    environment:
       - ACCEPT_EULA=Y
    ports:
       - 5341:5341
       - 8081:80